/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "label-mono": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      colors: {
        background: "var(--c-background)",
        primary: "var(--c-primary)",
        "on-primary": "var(--c-on-primary)",
        "primary-container": "var(--c-primary-container)",
        "on-primary-container": "var(--c-on-primary-container)",
        "primary-fixed": "var(--c-primary-fixed)",
        "primary-fixed-dim": "var(--c-primary-fixed-dim)",
        "on-primary-fixed": "var(--c-on-primary-fixed)",
        "on-primary-fixed-variant": "var(--c-on-primary-fixed-variant)",
        secondary: "var(--c-secondary)",
        "on-secondary": "var(--c-on-secondary)",
        "secondary-container": "var(--c-secondary-container)",
        "on-secondary-container": "var(--c-on-secondary-container)",
        "secondary-fixed": "var(--c-secondary-fixed)",
        "secondary-fixed-dim": "var(--c-secondary-fixed-dim)",
        "on-secondary-fixed": "var(--c-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--c-on-secondary-fixed-variant)",
        tertiary: "var(--c-tertiary)",
        "on-tertiary": "var(--c-on-tertiary)",
        "tertiary-container": "var(--c-tertiary-container)",
        "on-tertiary-container": "var(--c-on-tertiary-container)",
        "tertiary-fixed": "var(--c-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--c-tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--c-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--c-on-tertiary-fixed-variant)",
        surface: "var(--c-surface)",
        "surface-dim": "var(--c-surface-dim)",
        "surface-bright": "var(--c-surface-bright)",
        "surface-container-lowest": "var(--c-surface-container-lowest)",
        "surface-container-low": "var(--c-surface-container-low)",
        "surface-container": "var(--c-surface-container)",
        "surface-container-high": "var(--c-surface-container-high)",
        "surface-container-highest": "var(--c-surface-container-highest)",
        "surface-variant": "var(--c-surface-variant)",
        "surface-tint": "var(--c-surface-tint)",
        "on-surface": "var(--c-on-surface)",
        "on-surface-variant": "var(--c-on-surface-variant)",
        "on-background": "var(--c-on-background)",
        outline: "var(--c-outline)",
        "outline-variant": "var(--c-outline-variant)",
        "inverse-surface": "var(--c-inverse-surface)",
        "inverse-on-surface": "var(--c-inverse-on-surface)",
        "inverse-primary": "var(--c-inverse-primary)",
        error: "var(--c-error)",
        "on-error": "var(--c-on-error)",
        "error-container": "var(--c-error-container)",
        "on-error-container": "var(--c-on-error-container)",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
    },
  },
  plugins: [],
};
