/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "label-mono": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      colors: {
        background: "#faf9f7",
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        secondary: "#5f5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e4e2e1",
        "on-secondary-container": "#656464",
        "secondary-fixed": "#e4e2e1",
        "secondary-fixed-dim": "#c8c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474747",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1b1b1b",
        "on-tertiary-container": "#848484",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-tertiary-fixed": "#1b1b1b",
        "on-tertiary-fixed-variant": "#474747",
        surface: "#faf9f7",
        "surface-dim": "#dadad8",
        "surface-bright": "#faf9f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "surface-container": "#efeeec",
        "surface-container-high": "#e9e8e6",
        "surface-container-highest": "#e3e2e0",
        "surface-variant": "#e3e2e0",
        "surface-tint": "#5e5e5e",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#4c4546",
        "on-background": "#1a1c1b",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1ef",
        "inverse-primary": "#c6c6c6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
    },
  },
  plugins: [],
};
